struct BenchScopeApp {
    view: AppView,
    adapters: Vec<AdapterInfo>,
    cpu_info: CpuInfo,
    selected_adapter: usize,
    size_text: String,
    gpu_intensity: GpuIntensity,
    validate_output: bool,
    estimate_cpu_time: bool,
    repeat_mode: RepeatMode,
    repeat_duration: RepeatDuration,
    results: Vec<BenchmarkResult>,
    log: Vec<String>,
    status: String,
    progress: f32,
    cpu_progress: f32,
    gpu_progress: f32,
    eta_text: String,
    rx: Receiver<WorkerEvent>,
    tx: Sender<WorkerEvent>,
    cancel: Option<Arc<AtomicBool>>,
    running: bool,
    repeat_running: bool,
    pending_vram_warning: Option<PendingVramWarning>,
    matrix_back_confirm: bool,
    stress_back_confirm: bool,
    drive_back_confirm: bool,
    ram_back_confirm: bool,
    battery_back_confirm: bool,
    network_back_confirm: bool,
    drive: DriveBenchmarkState,
    storage_health_back_confirm: bool,
    storage_health: StorageHealthState,
    ram: RamTestState,
    battery: BatteryDiagnosticState,
    network: NetworkDiagnosticState,
    sensors: SensorManager,
    temperature_run: Option<TemperatureRunTracker>,
    fullscreen: bool,
    sensor_permission_prompt: bool,
}

include!("view.rs");
include!("common.rs");
include!("window.rs");
include!("runtime.rs");
